# Change these first
owner: neurobagel # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website (https://neurobagel.org/)
    url: https://neurobagel.org/
  - name: Public federation API (https://federate.neurobagel.org/)
    url: https://federate.neurobagel.org/
  - name: Public query tool (https://query.neurobagel.org/)
    url: https://query.neurobagel.org/
  - name: Annotation tool (https://annotate.neurobagel.org/)
    url: https://annotate.neurobagel.org/
  - name: Neurobagel OpenNeuro node (https://api.neurobagel.org/)
    url: https://api.neurobagel.org/
  - name: Neurobagel INDI node (https://indi.neurobagel.org/)
    url: https://indi.neurobagel.org/
  - name: Neurobagel QPN node 
    url: http://206.12.89.194:8080/
  - name: Digest dashboard
    url: https://digest.neurobagel.org/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.neurobagel.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/neurobagel/upptime/main/assets/neurobagel_logo.svg
  name: Neurobagel
  introTitle: "**Neurobagel** is an ecosystem for secure, federated research data management."
  introMessage: This is a status page which uses **real-time** data from Neurobagel services. See also our [GitHub repositories](https://github.com/neurobagel).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
